global:
  scrape_interval: 10s
scrape_configs:
  #  - job_name: 'nodejs'
  #    honor_labels: true
  #    static_configs:
  #      - targets: ['backend:3000']
  #  - job_name: "mongodb"
  #    honor_labels: true
  #    static_configs:
  #      - targets: ['mongo-exporter:9091']
  #  - job_name: "postgres"
  #    scrape_timeout: 9s
  #    honor_labels: true
  #    static_configs:
  #      - targets: ['pg-exporter:9092']
  - job_name: "tempo"
    scrape_timeout: 9s
    honor_labels: true
    static_configs:
      - targets: ["tempo:3100"]
#  - job_name: 'otel-collector'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['192.168.1.36:8889']
#      - targets: ['192.168.1.36:8888']
# - job_name: 'message-service-isolated'
#   scrape_interval: 10s
#   static_configs:
#     - targets: ['localhost:51920']
